import Head from 'next/head';

import Link from 'next/link';

export default function Home () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href={"/about"}>
        About
      </Link>

      <p> {process.env.API_URL} </p>
    </div>
  )
}